#!/usr/bin/env python 
# -*- coding: utf-8 -*-

import os
os.chdir("/usr/share/labtests/src")
import subprocess

p = subprocess.Popen(["python", "MainWindow.py"], stdout=subprocess.PIPE)

out, err = p.communicate()
print(out)
